## Append samples of your project ##
resources:
- models_v1alpha1_basetenmodel.yaml
- models_v1alpha1_basetenmodel_with_autoscaling.yaml
- models_v1alpha1_basetenmodel_with_trussconfig.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
