//go:build !ignore_autogenerated

/*
Copyright 2025 Abridge AI, Inc. and Baseten, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingConfig) DeepCopyInto(out *AutoscalingConfig) {
	*out = *in
	if in.MinReplicas != nil {
		in, out := &in.MinReplicas, &out.MinReplicas
		*out = new(int32)
		**out = **in
	}
	if in.MaxReplicas != nil {
		in, out := &in.MaxReplicas, &out.MaxReplicas
		*out = new(int32)
		**out = **in
	}
	if in.ConcurrencyTarget != nil {
		in, out := &in.ConcurrencyTarget, &out.ConcurrencyTarget
		*out = new(int32)
		**out = **in
	}
	if in.AutoscalingWindow != nil {
		in, out := &in.AutoscalingWindow, &out.AutoscalingWindow
		*out = new(int32)
		**out = **in
	}
	if in.ScaleDownDelay != nil {
		in, out := &in.ScaleDownDelay, &out.ScaleDownDelay
		*out = new(int32)
		**out = **in
	}
	if in.TargetUtilizationPercentage != nil {
		in, out := &in.TargetUtilizationPercentage, &out.TargetUtilizationPercentage
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingConfig.
func (in *AutoscalingConfig) DeepCopy() *AutoscalingConfig {
	if in == nil {
		return nil
	}
	out := new(AutoscalingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BasetenModel) DeepCopyInto(out *BasetenModel) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BasetenModel.
func (in *BasetenModel) DeepCopy() *BasetenModel {
	if in == nil {
		return nil
	}
	out := new(BasetenModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BasetenModel) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BasetenModelList) DeepCopyInto(out *BasetenModelList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BasetenModel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BasetenModelList.
func (in *BasetenModelList) DeepCopy() *BasetenModelList {
	if in == nil {
		return nil
	}
	out := new(BasetenModelList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BasetenModelList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BasetenModelSpec) DeepCopyInto(out *BasetenModelSpec) {
	*out = *in
	if in.TrussConfig != nil {
		in, out := &in.TrussConfig, &out.TrussConfig
		*out = new(TrussConfig)
		(*in).DeepCopyInto(*out)
	}
	in.Environment.DeepCopyInto(&out.Environment)
	if in.OrphanDeploymentCleanup != nil {
		in, out := &in.OrphanDeploymentCleanup, &out.OrphanDeploymentCleanup
		*out = new(OrphanDeploymentCleanupConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BasetenModelSpec.
func (in *BasetenModelSpec) DeepCopy() *BasetenModelSpec {
	if in == nil {
		return nil
	}
	out := new(BasetenModelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BasetenModelStatus) DeepCopyInto(out *BasetenModelStatus) {
	*out = *in
	if in.TrussPushTime != nil {
		in, out := &in.TrussPushTime, &out.TrussPushTime
		*out = (*in).DeepCopy()
	}
	if in.LastCleanupTime != nil {
		in, out := &in.LastCleanupTime, &out.LastCleanupTime
		*out = (*in).DeepCopy()
	}
	if in.FirstDeploymentFailureTime != nil {
		in, out := &in.FirstDeploymentFailureTime, &out.FirstDeploymentFailureTime
		*out = (*in).DeepCopy()
	}
	if in.NextRetryTime != nil {
		in, out := &in.NextRetryTime, &out.NextRetryTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BasetenModelStatus.
func (in *BasetenModelStatus) DeepCopy() *BasetenModelStatus {
	if in == nil {
		return nil
	}
	out := new(BasetenModelStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapKeyRef) DeepCopyInto(out *ConfigMapKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapKeyRef.
func (in *ConfigMapKeyRef) DeepCopy() *ConfigMapKeyRef {
	if in == nil {
		return nil
	}
	out := new(ConfigMapKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentConfig) DeepCopyInto(out *EnvironmentConfig) {
	*out = *in
	if in.Autoscaling != nil {
		in, out := &in.Autoscaling, &out.Autoscaling
		*out = new(AutoscalingConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.PromotionSettings != nil {
		in, out := &in.PromotionSettings, &out.PromotionSettings
		*out = new(PromotionSettingsConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentConfig.
func (in *EnvironmentConfig) DeepCopy() *EnvironmentConfig {
	if in == nil {
		return nil
	}
	out := new(EnvironmentConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrphanDeploymentCleanupConfig) DeepCopyInto(out *OrphanDeploymentCleanupConfig) {
	*out = *in
	if in.ScaleToZero != nil {
		in, out := &in.ScaleToZero, &out.ScaleToZero
		*out = new(bool)
		**out = **in
	}
	if in.Delete != nil {
		in, out := &in.Delete, &out.Delete
		*out = new(bool)
		**out = **in
	}
	if in.DeleteAfterDays != nil {
		in, out := &in.DeleteAfterDays, &out.DeleteAfterDays
		*out = new(int32)
		**out = **in
	}
	if in.MinToKeep != nil {
		in, out := &in.MinToKeep, &out.MinToKeep
		*out = new(int32)
		**out = **in
	}
	if in.IntervalMinutes != nil {
		in, out := &in.IntervalMinutes, &out.IntervalMinutes
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrphanDeploymentCleanupConfig.
func (in *OrphanDeploymentCleanupConfig) DeepCopy() *OrphanDeploymentCleanupConfig {
	if in == nil {
		return nil
	}
	out := new(OrphanDeploymentCleanupConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromotionSettingsConfig) DeepCopyInto(out *PromotionSettingsConfig) {
	*out = *in
	if in.ScaleDownPreviousDeployment != nil {
		in, out := &in.ScaleDownPreviousDeployment, &out.ScaleDownPreviousDeployment
		*out = new(bool)
		**out = **in
	}
	if in.PreserveInstanceType != nil {
		in, out := &in.PreserveInstanceType, &out.PreserveInstanceType
		*out = new(bool)
		**out = **in
	}
	if in.RedeployOnPromotion != nil {
		in, out := &in.RedeployOnPromotion, &out.RedeployOnPromotion
		*out = new(bool)
		**out = **in
	}
	if in.RollingDeploy != nil {
		in, out := &in.RollingDeploy, &out.RollingDeploy
		*out = new(bool)
		**out = **in
	}
	if in.PromotionCleanupStrategy != nil {
		in, out := &in.PromotionCleanupStrategy, &out.PromotionCleanupStrategy
		*out = new(string)
		**out = **in
	}
	if in.RampUpWhilePromoting != nil {
		in, out := &in.RampUpWhilePromoting, &out.RampUpWhilePromoting
		*out = new(bool)
		**out = **in
	}
	if in.RampUpDurationSeconds != nil {
		in, out := &in.RampUpDurationSeconds, &out.RampUpDurationSeconds
		*out = new(int32)
		**out = **in
	}
	if in.RollingDeployConfig != nil {
		in, out := &in.RollingDeployConfig, &out.RollingDeployConfig
		*out = new(RollingDeployConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromotionSettingsConfig.
func (in *PromotionSettingsConfig) DeepCopy() *PromotionSettingsConfig {
	if in == nil {
		return nil
	}
	out := new(PromotionSettingsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RollingDeployConfig) DeepCopyInto(out *RollingDeployConfig) {
	*out = *in
	if in.Strategy != nil {
		in, out := &in.Strategy, &out.Strategy
		*out = new(string)
		**out = **in
	}
	if in.MaxSurgePercent != nil {
		in, out := &in.MaxSurgePercent, &out.MaxSurgePercent
		*out = new(int32)
		**out = **in
	}
	if in.MaxUnavailablePercent != nil {
		in, out := &in.MaxUnavailablePercent, &out.MaxUnavailablePercent
		*out = new(int32)
		**out = **in
	}
	if in.StabilizationTimeSeconds != nil {
		in, out := &in.StabilizationTimeSeconds, &out.StabilizationTimeSeconds
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RollingDeployConfig.
func (in *RollingDeployConfig) DeepCopy() *RollingDeployConfig {
	if in == nil {
		return nil
	}
	out := new(RollingDeployConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SetupScriptSource) DeepCopyInto(out *SetupScriptSource) {
	*out = *in
	if in.ConfigMapRef != nil {
		in, out := &in.ConfigMapRef, &out.ConfigMapRef
		*out = new(ConfigMapKeyRef)
		**out = **in
	}
	if in.Inline != nil {
		in, out := &in.Inline, &out.Inline
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SetupScriptSource.
func (in *SetupScriptSource) DeepCopy() *SetupScriptSource {
	if in == nil {
		return nil
	}
	out := new(SetupScriptSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrussBaseImage) DeepCopyInto(out *TrussBaseImage) {
	*out = *in
	if in.DockerAuth != nil {
		in, out := &in.DockerAuth, &out.DockerAuth
		*out = new(TrussDockerAuth)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrussBaseImage.
func (in *TrussBaseImage) DeepCopy() *TrussBaseImage {
	if in == nil {
		return nil
	}
	out := new(TrussBaseImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrussConfig) DeepCopyInto(out *TrussConfig) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Secrets != nil {
		in, out := &in.Secrets, &out.Secrets
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.EnvironmentVariables != nil {
		in, out := &in.EnvironmentVariables, &out.EnvironmentVariables
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.BaseImage.DeepCopyInto(&out.BaseImage)
	if in.DockerServer != nil {
		in, out := &in.DockerServer, &out.DockerServer
		*out = new(TrussDockerServer)
		(*in).DeepCopyInto(*out)
	}
	if in.Runtime != nil {
		in, out := &in.Runtime, &out.Runtime
		*out = new(TrussRuntime)
		(*in).DeepCopyInto(*out)
	}
	if in.ModelMetadata != nil {
		in, out := &in.ModelMetadata, &out.ModelMetadata
		*out = new(TrussModelMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.SetupScript != nil {
		in, out := &in.SetupScript, &out.SetupScript
		*out = new(SetupScriptSource)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrussConfig.
func (in *TrussConfig) DeepCopy() *TrussConfig {
	if in == nil {
		return nil
	}
	out := new(TrussConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrussDockerAuth) DeepCopyInto(out *TrussDockerAuth) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrussDockerAuth.
func (in *TrussDockerAuth) DeepCopy() *TrussDockerAuth {
	if in == nil {
		return nil
	}
	out := new(TrussDockerAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrussDockerServer) DeepCopyInto(out *TrussDockerServer) {
	*out = *in
	if in.NoBuild != nil {
		in, out := &in.NoBuild, &out.NoBuild
		*out = new(bool)
		**out = **in
	}
	if in.ServerPort != nil {
		in, out := &in.ServerPort, &out.ServerPort
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrussDockerServer.
func (in *TrussDockerServer) DeepCopy() *TrussDockerServer {
	if in == nil {
		return nil
	}
	out := new(TrussDockerServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrussModelMetadata) DeepCopyInto(out *TrussModelMetadata) {
	*out = *in
	if in.ExampleModelInput != nil {
		in, out := &in.ExampleModelInput, &out.ExampleModelInput
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrussModelMetadata.
func (in *TrussModelMetadata) DeepCopy() *TrussModelMetadata {
	if in == nil {
		return nil
	}
	out := new(TrussModelMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrussResources) DeepCopyInto(out *TrussResources) {
	*out = *in
	if in.UseGpu != nil {
		in, out := &in.UseGpu, &out.UseGpu
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrussResources.
func (in *TrussResources) DeepCopy() *TrussResources {
	if in == nil {
		return nil
	}
	out := new(TrussResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrussRuntime) DeepCopyInto(out *TrussRuntime) {
	*out = *in
	if in.PredictConcurrency != nil {
		in, out := &in.PredictConcurrency, &out.PredictConcurrency
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrussRuntime.
func (in *TrussRuntime) DeepCopy() *TrussRuntime {
	if in == nil {
		return nil
	}
	out := new(TrussRuntime)
	in.DeepCopyInto(out)
	return out
}
