apiVersion: v2
name: baseten-operator
description: Kubernetes operator for managing Baseten model deployments
type: application
version: 0.3.7
appVersion: "v0.3.7"
kubeVersion: ">=1.28.0-0"
keywords:
  - baseten
  - operator
  - machine-learning
  - model-serving
  - gitops
home: https://github.com/abridgeai/baseten-operator
sources:
  - https://github.com/abridgeai/baseten-operator
maintainers:
  - name: Abridge AI
    url: https://github.com/abridgeai
icon: https://avatars.githubusercontent.com/u/69411042
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/operator: "true"
  artifacthub.io/operatorCapabilities: Basic Install
